// Code generated by protoc-gen-go. DO NOT EDIT.
// source: urlapi.proto

package urlapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShortenRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenRequest) Reset()         { *m = ShortenRequest{} }
func (m *ShortenRequest) String() string { return proto.CompactTextString(m) }
func (*ShortenRequest) ProtoMessage()    {}
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b26b703ca8ea2, []int{0}
}

func (m *ShortenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenRequest.Unmarshal(m, b)
}
func (m *ShortenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenRequest.Marshal(b, m, deterministic)
}
func (m *ShortenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenRequest.Merge(m, src)
}
func (m *ShortenRequest) XXX_Size() int {
	return xxx_messageInfo_ShortenRequest.Size(m)
}
func (m *ShortenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenRequest proto.InternalMessageInfo

func (m *ShortenRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type LengthenRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LengthenRequest) Reset()         { *m = LengthenRequest{} }
func (m *LengthenRequest) String() string { return proto.CompactTextString(m) }
func (*LengthenRequest) ProtoMessage()    {}
func (*LengthenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b26b703ca8ea2, []int{1}
}

func (m *LengthenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LengthenRequest.Unmarshal(m, b)
}
func (m *LengthenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LengthenRequest.Marshal(b, m, deterministic)
}
func (m *LengthenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LengthenRequest.Merge(m, src)
}
func (m *LengthenRequest) XXX_Size() int {
	return xxx_messageInfo_LengthenRequest.Size(m)
}
func (m *LengthenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LengthenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LengthenRequest proto.InternalMessageInfo

func (m *LengthenRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShortenResponse struct {
	Shorturl             string   `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenResponse) Reset()         { *m = ShortenResponse{} }
func (m *ShortenResponse) String() string { return proto.CompactTextString(m) }
func (*ShortenResponse) ProtoMessage()    {}
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b26b703ca8ea2, []int{2}
}

func (m *ShortenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenResponse.Unmarshal(m, b)
}
func (m *ShortenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenResponse.Marshal(b, m, deterministic)
}
func (m *ShortenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenResponse.Merge(m, src)
}
func (m *ShortenResponse) XXX_Size() int {
	return xxx_messageInfo_ShortenResponse.Size(m)
}
func (m *ShortenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenResponse proto.InternalMessageInfo

func (m *ShortenResponse) GetShorturl() string {
	if m != nil {
		return m.Shorturl
	}
	return ""
}

func (m *ShortenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LengthenResponse struct {
	Longurl              string   `protobuf:"bytes,1,opt,name=longurl,proto3" json:"longurl,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LengthenResponse) Reset()         { *m = LengthenResponse{} }
func (m *LengthenResponse) String() string { return proto.CompactTextString(m) }
func (*LengthenResponse) ProtoMessage()    {}
func (*LengthenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20b26b703ca8ea2, []int{3}
}

func (m *LengthenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LengthenResponse.Unmarshal(m, b)
}
func (m *LengthenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LengthenResponse.Marshal(b, m, deterministic)
}
func (m *LengthenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LengthenResponse.Merge(m, src)
}
func (m *LengthenResponse) XXX_Size() int {
	return xxx_messageInfo_LengthenResponse.Size(m)
}
func (m *LengthenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LengthenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LengthenResponse proto.InternalMessageInfo

func (m *LengthenResponse) GetLongurl() string {
	if m != nil {
		return m.Longurl
	}
	return ""
}

func (m *LengthenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ShortenRequest)(nil), "ShortenRequest")
	proto.RegisterType((*LengthenRequest)(nil), "LengthenRequest")
	proto.RegisterType((*ShortenResponse)(nil), "ShortenResponse")
	proto.RegisterType((*LengthenResponse)(nil), "LengthenResponse")
}

func init() { proto.RegisterFile("urlapi.proto", fileDescriptor_c20b26b703ca8ea2) }

var fileDescriptor_c20b26b703ca8ea2 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2d, 0xca, 0x49,
	0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0x0b, 0xce, 0xc8, 0x2f,
	0x2a, 0x49, 0xcd, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0x2d,
	0xca, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x94, 0xb9, 0xf8, 0x7d, 0x52,
	0xf3, 0xd2, 0x4b, 0x32, 0xf0, 0x29, 0x72, 0xe6, 0xe2, 0x87, 0x1b, 0x54, 0x5c, 0x90, 0x9f, 0x57,
	0x9c, 0x2a, 0x24, 0xc5, 0xc5, 0x51, 0x0c, 0x12, 0x42, 0xa8, 0x84, 0xf3, 0x85, 0x44, 0xb8, 0x58,
	0x53, 0x8b, 0x8a, 0xf2, 0x8b, 0x24, 0x98, 0xc0, 0x12, 0x10, 0x8e, 0x92, 0x13, 0x97, 0x00, 0xc2,
	0x26, 0xa8, 0x29, 0x12, 0x5c, 0xec, 0x39, 0xf9, 0x79, 0xe9, 0x08, 0x43, 0x60, 0x5c, 0xec, 0x66,
	0x18, 0x15, 0x71, 0x09, 0x42, 0x1d, 0xe2, 0x18, 0xe0, 0x19, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c,
	0x2a, 0xa4, 0xc3, 0xc5, 0x0e, 0x15, 0x14, 0xe2, 0xd7, 0x43, 0xf5, 0xb0, 0x94, 0x80, 0x1e, 0xba,
	0xc3, 0xf5, 0xb9, 0x38, 0x60, 0xce, 0x10, 0x12, 0xd0, 0x43, 0xf3, 0xbb, 0x94, 0xa0, 0x1e, 0xba,
	0x1b, 0x93, 0xd8, 0xc0, 0x81, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x01, 0x5b, 0xb5,
	0x5c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShortenAPIServiceClient is the client API for ShortenAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenAPIServiceClient interface {
	Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
	Lengthen(ctx context.Context, in *LengthenRequest, opts ...grpc.CallOption) (*LengthenResponse, error)
}

type shortenAPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewShortenAPIServiceClient(cc *grpc.ClientConn) ShortenAPIServiceClient {
	return &shortenAPIServiceClient{cc}
}

func (c *shortenAPIServiceClient) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	out := new(ShortenResponse)
	err := c.cc.Invoke(ctx, "/ShortenAPIService/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenAPIServiceClient) Lengthen(ctx context.Context, in *LengthenRequest, opts ...grpc.CallOption) (*LengthenResponse, error) {
	out := new(LengthenResponse)
	err := c.cc.Invoke(ctx, "/ShortenAPIService/Lengthen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenAPIServiceServer is the server API for ShortenAPIService service.
type ShortenAPIServiceServer interface {
	Shorten(context.Context, *ShortenRequest) (*ShortenResponse, error)
	Lengthen(context.Context, *LengthenRequest) (*LengthenResponse, error)
}

// UnimplementedShortenAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShortenAPIServiceServer struct {
}

func (*UnimplementedShortenAPIServiceServer) Shorten(ctx context.Context, req *ShortenRequest) (*ShortenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}
func (*UnimplementedShortenAPIServiceServer) Lengthen(ctx context.Context, req *LengthenRequest) (*LengthenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lengthen not implemented")
}

func RegisterShortenAPIServiceServer(s *grpc.Server, srv ShortenAPIServiceServer) {
	s.RegisterService(&_ShortenAPIService_serviceDesc, srv)
}

func _ShortenAPIService_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenAPIServiceServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortenAPIService/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenAPIServiceServer).Shorten(ctx, req.(*ShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenAPIService_Lengthen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LengthenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenAPIServiceServer).Lengthen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortenAPIService/Lengthen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenAPIServiceServer).Lengthen(ctx, req.(*LengthenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShortenAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShortenAPIService",
	HandlerType: (*ShortenAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _ShortenAPIService_Shorten_Handler,
		},
		{
			MethodName: "Lengthen",
			Handler:    _ShortenAPIService_Lengthen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "urlapi.proto",
}
